#!/usr/bin/env python

from httpdhs.http import Server
from httpdhs.partitioning import ConsistentHashingPartitioningStrategy
from httpdhs.backend import KeyValueController, KeyValueDatabase
from httpdhs.client import Client
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-p", "--port", dest="port", help="run on port PORT", metavar="PORT")
(options, args) = parser.parse_args()

client = Client()
database = KeyValueDatabase()
strategy = ConsistentHashingPartitioningStrategy(
    ["localhost:1234", "localhost:4321"], replicas=3)
node_name = "localhost:%s" % (options.port)
backend = KeyValueController(node_name, strategy, client, database)
Server(backend).run(options.port)

print "Done."
